Saulparedes/genpolicy sync [DO NOT MERGE]
microsoft/kata-containers pull request #170
Opened 2024-04-08 22:34 UTC by Redent0r

###### Merge Checklist  

- [ ] Followed patch format from upstream recommendation: https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format
  - [ ] Included a single commit in a given PR - at least unless there are related commits and each makes sense as a change on its own.
- [ ] Aware about the PR to be merged using "create a merge commit" rather than "squash and merge" (or similar)
- [ ] genPolicy only: Ensured the tool still builds on Windows
- [ ] genPolicy only: Updated sample YAMLs' policy annotations, if applicable
- [ ] The `upstream-missing` label (or `upstream-not-needed`) has been set on the PR. 

###### Summary 

###### Associated issues  

###### Links to CVEs  

###### Test Methodology

2024-04-08 22:37 UTC, Redent0r commented
Do not merge until changes in https://github.com/kata-containers/kata-containers/pull/9185/commits are incorporated

2024-04-08 22:59 UTC, danmihai1 requested changes
I think you should split this PR in smaller pieces, that are easier to review, test, debug.

2024-04-08 22:59 UTC, danmihai1 commented on src/tools/genpolicy/genpolicy-advanced-command-line-parameters.md
> +By default, the `genpolicy` input files [`rules.rego`](rules.rego) and [`genpolicy-settings.json`](genpolicy-settings.json) must be present in the current directory - otherwise `genpolicy` returns an
This breaking change requires a corresponding change in az confcom. Seth didn't mind making this change several weeks ago, but we need to sync up with him again.

2024-04-08 22:59 UTC, danmihai1 commented on src/tools/genpolicy/genpolicy-advanced-command-line-parameters.md
> +$ genpolicy -p /tmp/rules.rego -j /tmp/genpolicy-settings.json -y test.yaml
Do we need to update MSFT tests for this?

2024-04-08 22:59 UTC, danmihai1 commented on src/tools/genpolicy/genpolicy-settings.json
> +            "mount_source": "^$(cpath)/$(sandbox-id)/rootfs/local/",
These paths might need to change when using confidential=true at MSFT. They are probably specific to main code on Mariner, *without* confidential enabled.

2024-04-08 22:59 UTC, danmihai1 commented on src/tools/genpolicy/genpolicy-settings.json
> +        "confidential_guest": false
I believe MSFT needs this to be true.

2024-04-08 22:59 UTC, danmihai1 commented on src/tools/genpolicy/src/config_map.rs
> -    fn get_namespace(&self) -> String {
Removing this code seems suspect at a quick look.

2024-04-09 16:42 UTC, closed without merging

2024-04-09 16:42 UTC, Redent0r commented
Closing for https://github.com/microsoft/kata-containers/pull/171